[package]
name = "sec-fetcher"
version = "0.1.0-alpha"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.40"
csv = "1.3.1"
email_address = "0.2.9"
indexmap = "2.7.1"
itertools = "0.14.0"
keyring = { version = "3.6.2", features = ["apple-native", "windows-native", "sync-secret-service"] }
once_cell = "1.20.3"
polars = { version = "0.46.0", features = ["json", "lazy", "pivot"] }
rand = "0.9.0"
rayon = "1.10.0"
reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0.140"
string-replace-all = "0.2.1"
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
mockito = "1.7.0"
