[package]
name = "sec-fetcher"
version = "0.1.0-alpha"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.10.1"
chrono = "0.4.40"
config = "0.15.9"
csv = "1.3.1"
dashmap = { version = "6.1.0", features = ["rayon"] }
dirs = "6.0.0"
email_address = "0.2.9"
indexmap = "2.7.1"
itertools = "0.14.0"
keyring = { version = "3.6.2", features = ["apple-native", "windows-native", "sync-secret-service"] }
merge = "0.1.0"
once_cell = "1.20.3"
polars = { version = "0.46.0", features = ["json", "lazy", "pivot"] }
quick-xml = "0.37.2"
rand = "0.9.0"
rayon = "1.10.0"
reqwest = { version = "0.12.12", features = ["json"] }
reqwest-drive = "0.1.0-alpha.6"
rust_decimal = { version = "1.36.0", features = ["serde"] }
rust_decimal_macros = "1.36.0"
schemars = "0.8.22"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
simd-r-drive = "0.3.0-alpha.1"
simd-r-drive-extensions = "0.4.0-alpha.3"
strum = "0.27.1"
strum_macros = "0.27.1"
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
mockito = "1.7.0"
tempfile = "3.18.0"
