import joblib
from io import BytesIO

import numpy as np
from typing import Tuple, Optional, Any


__all__ = [
    "encode_string_to_bytes",
    "decode_string_from_bytes",
    "encode_u32_to_raw_bytes",
    "decode_u32_from_raw_bytes",
    "encode_float_to_raw_bytes",
    "decode_float_from_bytes",
    "encode_numpy_array_to_raw_bytes",
    "decode_numpy_array_from_bytes",
    "encode_joblib_object_to_bytes",
    "decode_joblib_object_from_bytes"
]

# Specifies how many bytes are used to store the length prefix for encoded strings.
# With 2 bytes, we can represent string lengths up to 65,535 bytes (uint16 range).
LEN_PREFIX_BYTES = 2


def encode_string_to_bytes(s: str) -> bytes:
    """Encodes a string into a byte sequence using the format: [2-byte little-endian length][UTF-8 data]."""
    s_bytes = s.encode("utf-8")
    s_len = len(s_bytes)
    if s_len > (2 ** (8 * LEN_PREFIX_BYTES) - 1):  # Check if length fits in prefix
        raise ValueError(
            f"String length {s_len} exceeds max for {LEN_PREFIX_BYTES} bytes prefix."
        )
    return s_len.to_bytes(LEN_PREFIX_BYTES, "little") + s_bytes


def decode_string_from_bytes(data: bytes, offset: int) -> Tuple[str, int]:
    """Decodes a length-prefixed string from a byte buffer, returning the string and the new offset."""
    s_len = int.from_bytes(data[offset : offset + LEN_PREFIX_BYTES], "little")
    offset += LEN_PREFIX_BYTES
    s = data[offset : offset + s_len].decode("utf-8")
    offset += s_len
    return s, offset

def encode_u32_to_raw_bytes(i: int) -> bytes:
    """Encodes an integer into a 4-byte (u32) little-endian sequence."""
    return i.to_bytes(4, "little", signed=False)

def decode_u32_from_raw_bytes(data: bytes) -> int:
    """Decodes a 4-byte little-endian sequence into a Python integer."""
    return int.from_bytes(data, "little", signed=False)

def encode_float_to_raw_bytes(f: float) -> bytes:
    """Encodes a float into its raw 8-byte (float64) sequence."""
    return np.array([f], dtype=np.float64).tobytes()

def decode_float_from_bytes(data: bytes) -> float:
    """Decodes an 8-byte sequence into a 64-bit float."""
    return np.frombuffer(data, dtype=np.float64)[0]

def encode_numpy_array_to_raw_bytes(
    arr: np.ndarray,
    as_type: Optional[np.dtype] = np.float64,
) -> bytes:
    """
    Serialize a NumPy array to raw bytes.

    Parameters
    ----------
    arr : np.ndarray
        Array to serialize.
    as_type : Optional[np.dtype], default np.float64
        • np.dtype → cast to this dtype before serialization.  
        • None     → keep arr.dtype unchanged.

    Returns
    -------
    bytes
        Contiguous byte sequence representing the (possibly cast) array.
    """
    if as_type is not None and arr.dtype != as_type:
        arr = arr.astype(as_type, copy=False)
    return np.ascontiguousarray(arr).tobytes()

def decode_numpy_array_from_bytes(
    data: bytes, dtype: np.dtype, shape: Optional[Tuple[int, ...]] = None
) -> np.ndarray:
    """Creates a NumPy array from a raw byte buffer, interpreting the data with a given dtype and optional shape."""
    arr = np.frombuffer(data, dtype=dtype)
    if shape:
        arr = arr.reshape(shape)
    return arr


def encode_joblib_object_to_bytes(obj: Any) -> bytes:
    """Serializes a Python object into a byte sequence using joblib."""
    buffer = BytesIO()
    joblib.dump(obj, buffer)
    return buffer.getvalue()


def decode_joblib_object_from_bytes(data: bytes) -> Any:
    """Deserializes a Python object from a joblib-generated byte sequence."""
    return joblib.load(BytesIO(data))
