use std::collections::HashMap;
use std::error::Error;
// use tokio;
pub mod network;
pub use network::{fetch_sec_tickers, fetch_ticker_fundamentals, SecClient};
pub mod accessor;
pub mod fs;
pub mod transform;
// use polars::prelude::{CsvWriter, SerWriter};
// use std::fs::File;
